[package]
name = "tw3-settings-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.19.0"
eframe = "0.19.0"
dirs = "4.0.0"
rust-ini = "0.18.0"
clipboard-win = "4.4.2"
